### PR TITLE
Fixed avoid_unused_parameters

### LINKED ISSUE #58: avoid-unused-parameters does not report parameters from typedef
Rule should report positional parameters from typedef if their name are not underscores.

Code below represents expected behavior.

```
typedef MaxFun = int Function(int a, int b);

// expect_lint: avoid-unused-parameters
final MaxFun maxFunLint = (int a, int b) => 1;
  
final MaxFun maxFunOk = (int _, int __) => 1;
```

### PR DESCRIPTION
**Pull request by Viktor-Mudrytskyi**
Closes #58

### CODE REVIEW

File: lint_test/avoid_unused_parameters_test.dart [hunk 1]
```diff
@@ -10,11 +10,44 @@ import 'package:flutter/material.dart';
...
+// expect_lint: avoid_unused_parameters
+final MaxFun bad = (int a, int b) => 1;
+
+final MaxFun good = (int a, _) => a;
+
+final MaxFun ok = (int _, int __) => 1;
+
+final MaxFun goodMax = (int a, int b) {
+  return a + b;
+};
```
Comment (yurii-prykhodko-solid) [inline lint_test/avoid_unused_parameters_test.dart:24]: Let's double-check how it works with named params -- we don't have the liberty to rename those to underscores.

**Review by yurii-prykhodko-solid — CHANGES_REQUESTED** [review]

File: lib/src/lints/avoid_unused_parameters/avoid_unused_parameters_rule.dart [hunk 2]
```diff
@@ -9,6 +9,11 @@ import 'package:solid_lints/src/models/solid_lint_rule.dart';
 /// ### Example:
 /// #### BAD:
 /// ```dart
+/// typedef MaxFun = int Function(int a, int b);
+/// final MaxFun bad = (int a, int b) => 1; // LINT
+/// final MaxFun tetsFun = (int a, int b) { // LINT
```
Comment (yurii-prykhodko-solid) [inline lib/src/lints/avoid_unused_parameters/avoid_unused_parameters_rule.dart:14]: typo
```suggestion
/// final MaxFun testFun = (int a, int b) { // LINT
```

File: lint_test/avoid_unused_parameters_test.dart [hunk 3]
```diff
@@ -10,11 +10,70 @@ import 'package:flutter/material.dart';
...
+
+// expect_lint: avoid_unused_parameters
+final Named _named = ({required text}) {
+  return '';
+};
```
Comment (yurii-prykhodko-solid) [inline lint_test/avoid_unused_parameters_test.dart:31]: Don't think this is what we want -- no good way to satisfy the lint in case we don't actually need to use a named parameter, which may be coming from a 3rd-party API that we have not control over.

Let's exclude named parameters from the lint for now.

**Review by yurii-prykhodko-solid — CHANGES_REQUESTED** [review]

**Review by yurii-prykhodko-solid — APPROVED** [review]
LGTM!

File: CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 - Added `avoid_using_debug_print` rule
 - Fixed an issue with no_magic_number lint
+- Fixed `avoid_unused_parameters` lint's bug regarding function variable assignment/declaration
```
Comment (illia-romanenko) [inline CHANGELOG.md:5]:
```suggestion
- Fixed `avoid_unused_parameters` to report positional parameters from typedef if their name are not underscores.
```
Or there was something else as well?

**Review by illia-romanenko — APPROVED** [review]
Looks nice, have one question/suggestion - let me know if that makes sense.
